spring:
  application:
    name: biblioteca
  profiles:
    active: local  # Cambiar a local para usar base de datos!!!!!!
                   # No se puede acceder a la base de datos con "dev"

server:
  port: 8080